### PR TITLE
update to csproj and asp.net 2.0

### PR DESCRIPTION
**Pull request by SychevIgor**
with vs2017 we can use csproj files instead of xproj that is not valid anymore for vs2017, only for vs2015

### CODE REVIEW

**Comment by sethreidnz** [comment]
Is this repo actively being maintained? I think this should be merged as soon as possible since its the only example of how to do this with Azure B2C available from the documentation and it doesn't work with the latest tools (CLI or VS 2017)

**Comment by gsacavdm** [comment]
@sethreidnz , RE:

> its the only example of ho to do this with Azure B2C

Actually, this sample is for Azure AD. For Azure AD B2C, there is an separate dotnet core sample  that has been update to dotnetcore 1.1: https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp

**Comment by SychevIgor** [comment]
@gsacavdm I'm totally agree that this repo is not about b2c, but still- 22 days nobody can merge pull requests... it's still look like repo not supported by microsoft.

Actually the same issue with all 5 repos, where we have xproj instead of csproj... Nobody wanna merge pull request with xproj->csproj migration....

https://github.com/Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore
https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore
https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore
https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore

**Comment by SychevIgor** [comment]
@heavenwing @tushargupta51 @dstrockis @priyamohanram any feedback?

**Comment by lundcm** [comment]
...

edit:
I feel like this should have happened quite some time ago, but having gone through the migration myself I was able to mostly understand the example from what's here. That isn't the case for a lot of people though and that number will continue to decline.

**Comment by mohamedmansour** [comment]
This project requires more updates, for example UseCookieAuthentication is obsolete in netcore2:

```
//
// Summary:
//     Obsolete, see https://go.microsoft.com/fwlink/?linkid=845470
//
// Parameters:
//   app:
//     The Microsoft.AspNetCore.Builder.IApplicationBuilder to add the handler to.
//
//   options:
//     A Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationOptions that
//     specifies options for the handler.
//
// Returns:
//     A reference to this instance after the operation has completed.
[Obsolete("See https://go.microsoft.com/fwlink/?linkid=845470", true)]
public static IApplicationBuilder UseCookieAuthentication(this IApplicationBuilder app, CookieAuthenticationOptions options);
```

**Comment by SychevIgor** [comment]
@mohamedmansour it's fixed in my latest commit. 
I thought that nobody care about this repo, since PR here from may 2017.

**Comment by mohamedmansour** [comment]
@danieldobalian can we merge this in please?

**Comment by SychevIgor** [comment]
@mohamedmansour @danieldobalian maybe you also can look on 
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore/pull/10
https://github.com/Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore/pull/6
https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2/pull/8
https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/pull/19

**Comment by danieldobalian** [comment]
@mohamedmansour thanks for the mention. I'll get a review started.

**Comment by jmprieur** [comment]
@mohamedmansour done, but in a separate branch for now (until customers/partners had time to update their tooling, as VS 2017.3 only release 2 days ago)

**Comment by mohamedmansour** [comment]
@jmprieur ah, you could make a branch dotnetcore1.1 that has everything prior to these changes, then master has all latest and greatest changes.  

But either way works, I rather have older stuff in branches/tags, either for new people to jump in and learn

**Pull request merged**
